apiVersion: v1
kind: Service
metadata:
  labels:
    app: python-helloworld
  name: python-helloworld
  namespace: demo
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
  selector:
    app: python-helloworld
  type: NodePort
